#!/usr/bin/env node
// The pack release program, split so the job holding the signing key never runs pack code:
//
//   node tools/release/release.mjs plan [--packs <dir>] [--repo <dir>] [--remote <name|url>]
//   node tools/release/release.mjs build --out <dir> [--packs <dir>]
//   node tools/release/release.mjs publish --archives <dir> --roots <dir> [--key <file> --cert <file>]
//                                  [--repo <dir>] [--remote <name|url>] [--summary <file>] [--now <instant>]
//
// `build` vendors every pack under --packs (default: this repo's packs/) into --out, with a
// packs.json describing them and a SHA256SUMS over both. `publish` checks SHA256SUMS first, then
// for each pack whose version is absent on the remote's `vendored` branch writes the unpacked set,
// the archive and a newly signed index as one commit, refuses a published version whose unpacked
// files differ (gzip bytes alone may differ), re-verifies every index it wrote against --roots, and pushes once. The signing key is
// --key/--cert, else the files CN_PACKS_KEY/CN_PACKS_CERT name, else the development key under
// keys/dev/. The R2 upload is a dry run listing the objects it would send. docs/release.md has
// the branch layout and index format.
import { execFileSync } from 'node:child_process';
import { createHash } from 'node:crypto';
import { appendFileSync, copyFileSync, existsSync, lstatSync, mkdirSync, readdirSync, readFileSync, unlinkSync, writeFileSync } from 'node:fs';
import { join, resolve } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';
import { keyId, parsePrivateKey, readRoots, SignError } from '../sign/sign.mjs';
import { BRANCH, fetchVendored, git, openBranch, ReleaseError } from './branch.mjs';
import { addVersion, assertSerialAdvances, IndexError, newIndex, packFields, readIndex, serialize, signIndex } from './index.mjs';

const REPO_ROOT = fileURLToPath(new URL('../../', import.meta.url));
const DEV_KEY = 'keys/dev/packs.key';
const DEV_CERT = 'keys/dev/packs.cert.json';
const BRANCH_README = `# vendored

Generated by \`.github/workflows/release-packs.yml\` and never edited by hand. Per pack:
\`<id>/<version>/\` is the vendored set unpacked, \`<id>/<version>.tar.gz\` the archive,
\`<id>/index.json\` the pack index and \`<id>/index.sig.json\` its signature. \`docs/release.md\` on
\`main\` describes the format.
`;

const sha256 = (buf) => createHash('sha256').update(buf).digest('hex');

function parseArgs(args, known) {
  const opts = {};
  for (let i = 0; i < args.length; i += 2) {
    const name = args[i]?.replace(/^--/, '');
    if (!args[i]?.startsWith('--') || !known.includes(name)) throw new ReleaseError(`unknown argument ${args[i]}`);
    if (args[i + 1] === undefined) throw new ReleaseError(`${args[i]} needs a value`);
    opts[name] = args[i + 1];
  }
  return opts;
}

// Every pack directory under packsDir with its pack.json fields, validated before anything is built.
function readPacks(packsDir) {
  const ids = readdirSync(packsDir).filter((n) => lstatSync(join(packsDir, n)).isDirectory()).sort();
  const packs = [];
  const errors = [];
  for (const id of ids) {
    try {
      const file = join(packsDir, id, 'pack.json');
      if (!existsSync(file)) throw new ReleaseError(`${id}: no pack.json`);
      let json;
      try { json = JSON.parse(readFileSync(file, 'utf8')); } catch (e) { throw new ReleaseError(`${id}: pack.json does not parse: ${e.message}`); }
      packs.push({ id, ...packFields(id, json) });
    } catch (e) {
      if (!(e instanceof ReleaseError || e instanceof IndexError)) throw e;
      errors.push(e.message);
    }
  }
  if (errors.length) throw new ReleaseError(errors.join('\n'));
  return packs;
}

const onBranch = (repo, commit, path) => commit !== null && (() => {
  try { git(repo, ['cat-file', '-e', `${commit}:${path}`]); return true; } catch { return false; }
})();

function plan(opts) {
  const packs = readPacks(resolve(opts.packs ?? join(REPO_ROOT, 'packs')));
  const repo = resolve(opts.repo ?? '.');
  const tip = fetchVendored(repo, opts.remote ?? 'origin');
  for (const p of packs) console.log(`${onBranch(repo, tip, `${p.id}/${p.version}`) ? 'published' : 'publish'} ${p.id} ${p.version}`);
  return 0;
}

async function build(opts) {
  if (!opts.out) throw new ReleaseError('build needs --out <dir>');
  const packsDir = resolve(opts.packs ?? join(REPO_ROOT, 'packs'));
  const out = resolve(opts.out);
  if (existsSync(out) && readdirSync(out).length) throw new ReleaseError(`${out} is not empty`);
  const packs = readPacks(packsDir);
  const sourceCommit = git(packsDir, ['rev-parse', 'HEAD']).trim();
  const { vendorPack } = await import('../vendor/vendor.mjs');
  const built = [];
  for (const p of packs) {
    const r = vendorPack(join(packsDir, p.id), out);
    const archive = `${p.id}-${p.version}.tar.gz`;
    unlinkSync(join(out, `${p.id}-${p.version}.sha256`));
    built.push({ ...p, archive, sha256: r.sha256, size: r.size });
    console.log(`built ${p.id} ${p.version} ${r.size} ${r.sha256}`);
  }
  writeFileSync(join(out, 'packs.json'), JSON.stringify({ sourceCommit, packs: built }, null, 2) + '\n');
  const sums = [...built.map((b) => `${b.sha256}  ${b.archive}`), `${sha256(readFileSync(join(out, 'packs.json')))}  packs.json`];
  writeFileSync(join(out, 'SHA256SUMS'), sums.join('\n') + '\n');
  console.log(`${built.length} packs built from ${sourceCommit}`);
  return 0;
}

function checkSums(dir) {
  const listed = new Map();
  for (const line of readFileSync(join(dir, 'SHA256SUMS'), 'utf8').split('\n').filter(Boolean)) {
    const m = /^([0-9a-f]{64}) {2}([^/]+)$/.exec(line);
    if (!m) throw new ReleaseError(`SHA256SUMS line is malformed: ${line}`);
    listed.set(m[2], m[1]);
  }
  for (const [file, hex] of listed) {
    if (!existsSync(join(dir, file)) || sha256(readFileSync(join(dir, file))) !== hex) throw new ReleaseError(`${file} does not match SHA256SUMS`);
  }
  if (!listed.has('packs.json')) throw new ReleaseError('SHA256SUMS does not cover packs.json');
  const manifest = JSON.parse(readFileSync(join(dir, 'packs.json'), 'utf8'));
  for (const p of manifest.packs) {
    if (listed.get(p.archive) !== p.sha256) throw new ReleaseError(`${p.archive} is not covered by SHA256SUMS`);
  }
  return manifest;
}

// Every regular file under dir as path -> "sha256 mode", mode reduced to 644 or 755 as the
// vendored set and git both record it.
function treeManifest(dir) {
  const out = new Map();
  const walk = (rel) => {
    for (const name of readdirSync(join(dir, rel)).sort()) {
      const path = rel ? `${rel}/${name}` : name;
      const st = lstatSync(join(dir, path));
      if (st.isDirectory()) walk(path);
      else out.set(path, `${sha256(readFileSync(join(dir, path)))} ${st.mode & 0o111 ? '755' : '644'}`);
    }
  };
  walk('');
  return out;
}

// What differs between the published tree and a candidate one, as "differing: …; missing: …;
// extra: …" with paths in byte order, or null when the two hold the same files.
export function compareTrees(published, candidate) {
  const a = treeManifest(published);
  const b = treeManifest(candidate);
  const byBytes = (x, y) => Buffer.compare(Buffer.from(x), Buffer.from(y));
  const differing = [...a.keys()].filter((k) => b.has(k) && a.get(k) !== b.get(k)).sort(byBytes);
  const missing = [...a.keys()].filter((k) => !b.has(k)).sort(byBytes);
  const extra = [...b.keys()].filter((k) => !a.has(k)).sort(byBytes);
  const parts = [['differing', differing], ['missing', missing], ['extra', extra]].filter(([, l]) => l.length).map(([n, l]) => `${n}: ${l.join(', ')}`);
  return parts.length ? parts.join('; ') : null;
}

// The instant the self-check verifies at: the clock, or --now, which exists for tests that sign
// with a certificate whose window is not today's. publishedAt never reads it.
function selfCheckInstant(now) {
  if (now === undefined) return new Date();
  const t = Date.parse(now);
  if (Number.isNaN(t)) throw new ReleaseError(`--now "${now}" is not a date`);
  return new Date(t);
}

function signingKey(opts) {
  const keyPath = opts.key ?? process.env.CN_PACKS_KEY;
  const certPath = opts.cert ?? process.env.CN_PACKS_CERT;
  if (!keyPath !== !certPath) throw new ReleaseError('CN_PACKS_KEY and CN_PACKS_CERT (or --key and --cert) are set together or not at all');
  const dev = !keyPath;
  if (dev) console.log(`signing with the development key ${DEV_KEY} (trusted by no member)`);
  const key = parsePrivateKey(readFileSync(dev ? join(REPO_ROOT, DEV_KEY) : keyPath, 'utf8'));
  const certificate = JSON.parse(readFileSync(dev ? join(REPO_ROOT, DEV_CERT) : certPath, 'utf8'));
  return { key, certificate, dev };
}

function publish(opts) {
  if (!opts.archives || !opts.roots) throw new ReleaseError('publish needs --archives <dir> and --roots <dir>');
  const archives = resolve(opts.archives);
  const manifest = checkSums(archives);
  const roots = readRoots(resolve(opts.roots));
  const { key, certificate, dev } = signingKey(opts);
  console.log(`signing key id ${keyId(key.publicKey)}`);
  const repo = resolve(opts.repo ?? '.');
  const remote = opts.remote ?? 'origin';
  const branch = openBranch(repo, remote);
  const { tree, scratch } = branch;
  try {

    const pending = [];
    const conflicts = [];
    for (const p of manifest.packs) {
      const indexFile = join(tree, p.id, 'index.json');
      const previous = existsSync(indexFile) ? readIndex(readFileSync(indexFile)) : null;
      const entry = previous?.versions.find((e) => e.version === p.version);
      if (entry || existsSync(join(tree, p.id, p.version))) {
        if (!entry) conflicts.push(`${p.id} ${p.version} is on ${BRANCH} but not in its index`);
        else if (!existsSync(join(tree, p.id, p.version))) conflicts.push(`${p.id} ${p.version} is in its index but its unpacked set is not on ${BRANCH}`);
        else if (entry.sha256 !== p.sha256) {
          const unpacked = join(scratch, 'compare', p.id);
          mkdirSync(unpacked, { recursive: true });
          execFileSync('tar', ['-xzf', join(archives, p.archive), '-C', unpacked]);
          const d = compareTrees(join(tree, p.id, p.version), unpacked);
          if (d) conflicts.push(`${p.id} ${p.version} is already published with different content (${d}). Bump the version.`);
        }
        continue;
      }
      pending.push({ ...p, previous });
    }
    if (conflicts.length) throw new ReleaseError(`refusing to overwrite a published version:\n${conflicts.join('\n')}`);
    if (!pending.length) {
      console.log('nothing to publish');
      writeSummary(opts.summary, [], key, dev);
      return 0;
    }

    const publishedAt = new Date().toISOString().replace(/\.\d{3}Z$/, 'Z');
    const written = [];
    for (const p of pending) {
      const dir = join(tree, p.id, p.version);
      mkdirSync(dir, { recursive: true });
      execFileSync('tar', ['-xzf', join(archives, p.archive), '-C', dir]);
      copyFileSync(join(archives, p.archive), join(tree, p.id, `${p.version}.tar.gz`));
      const next = addVersion(p.previous ?? newIndex(p.id), {
        packJson: { version: p.version, minEngineVersion: p.minEngineVersion, requires: p.requires },
        sha256: p.sha256, size: p.size, publishedAt, sourceCommit: manifest.sourceCommit,
      });
      assertSerialAdvances(p.previous, next);
      const bytes = serialize(next);
      writeFileSync(join(tree, p.id, 'index.json'), bytes);
      writeFileSync(join(tree, p.id, 'index.sig.json'), JSON.stringify(signIndex(bytes, key, certificate), null, 2) + '\n');
      if (!existsSync(join(tree, 'README.md'))) writeFileSync(join(tree, 'README.md'), BRANCH_README);
      branch.writeBranchCommit([p.id, 'README.md'], `Release ${p.id} ${p.version}`);
      written.push({ ...p, serial: next.serial });
      console.log(`Release ${p.id} ${p.version}`);
    }

    branch.selfCheck(written, roots, selfCheckInstant(opts.now));
    branch.push();
    console.log(`pushed ${written.length} release commit(s) to ${BRANCH}`);

    console.log('R2 upload (dry run until ClaudinitePacks#1):');
    for (const p of written) {
      console.log(`would PUT packs/${p.id}/${p.version}.tar.gz (${p.size} bytes, sha256 ${p.sha256})`);
      console.log(`would PUT packs/${p.id}/index.json`);
      console.log(`would PUT packs/${p.id}/index.sig.json`);
    }
    writeSummary(opts.summary, written, key, dev);
    return 0;
  } finally {
    branch.close();
  }
}

function writeSummary(file, written, key, dev) {
  if (!file) return;
  const lines = [
    '## Pack release',
    '',
    `Signing key id \`${keyId(key.publicKey)}\`${dev ? ' (the development key, trusted by no member)' : ''}.`,
    '',
    written.length ? `${written.length} pack version(s) published:` : 'Nothing to publish.',
    ...written.map((p) => `- ${p.id} ${p.version} (index serial ${p.serial})`),
    '',
  ];
  appendFileSync(file, lines.join('\n'));
}

async function main([cmd, ...args]) {
  if (cmd === 'plan') return plan(parseArgs(args, ['packs', 'repo', 'remote']));
  if (cmd === 'build') return build(parseArgs(args, ['packs', 'out']));
  if (cmd === 'publish') return publish(parseArgs(args, ['archives', 'roots', 'key', 'cert', 'repo', 'remote', 'summary', 'now']));
  console.error('usage: release.mjs plan | build --out <dir> | publish --archives <dir> --roots <dir> (see the header)');
  return 2;
}

if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
  main(process.argv.slice(2)).then((code) => { process.exitCode = code; }).catch((e) => {
    if (!(e instanceof ReleaseError || e instanceof IndexError || e instanceof SignError || e.code === 'ENOENT')) throw e;
    console.error(`release.mjs: ${e.message}`);
    process.exitCode = 1;
  });
}
