#!/usr/bin/env node
// The pack release program, split so the job holding the signing key never runs pack code:
//
//   node tools/release/release.mjs plan [--content] [--packs <dir>] [--repo <dir>]
//                                  [--remote <name|url>]
//   node tools/release/release.mjs build --out <dir> [--packs <dir>]
//   node tools/release/release.mjs publish --archives <dir> --roots <dir>
//                                  [--key <file> --cert <file>] [--repo <dir>]
//                                  [--remote <name|url>] [--summary <file>] [--now <instant>]
//   node tools/release/release.mjs upload --r2 <bucket|dry-run> --roots <dir>
//                                  [--repo <dir>] [--remote <name|url>] [--summary <file>]
//   node tools/release/release.mjs evidence --out <file> [--canaries <file>]
//                                  [--repo] [--remote] [--summary]
//   node tools/release/release.mjs promote --evidence <file> --roots <dir>
//                                  [--canaries <file>] [...]
//   node tools/release/release.mjs promote|revoke --pack <id> --version <v> --by <login>
//                                  --roots <dir> [...]
//
// `plan` says per pack whether its version is to publish or already on `vendored`; with
// --content it also vendors each published pack afresh and exits 1 when the files differ from the
// branch's, the pull-request half of "a version is published once". `build` vendors every pack
// under --packs (default: this repo's packs/) into --out, with a packs.json describing them and a
// SHA256SUMS over both. `publish` checks SHA256SUMS first, then for each pack whose version is
// absent on the remote's `vendored` branch writes the unpacked set, the archive and a newly signed
// index as one commit, refuses a published version whose unpacked files differ (the gzip bytes
// alone may), re-verifies every index it wrote against --roots, and pushes once. --now moves only
// that self-check's instant, for tests. The signing key is --key/--cert, else the files
// CN_PACKS_KEY/CN_PACKS_CERT name, else the development key under keys/dev/. `upload` makes the
// R2 bucket hold every object on the branch and reads them back through the CDN (r2.mjs);
// `dry-run` lists them. `evidence`, `promote` and `revoke` read canary evidence and rewrite index
// entries (promote.mjs), signing as publish does. docs/release.md has the layout and formats.
import { execFileSync } from 'node:child_process';
import { createHash } from 'node:crypto';
import { appendFileSync, copyFileSync, existsSync, lstatSync, mkdirSync, mkdtempSync, readdirSync, readFileSync, rmSync, unlinkSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join, resolve } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';
import { keyId, parsePrivateKey, readRoots, SignError } from '../sign/sign.mjs';
import { BRANCH, fetchVendored, git, openBranch, packIds, ReleaseError, showFile } from './branch.mjs';
import { addVersion, assertSerialAdvances, IndexError, newIndex, packFields, readIndex, serialize, signIndex } from './index.mjs';
import { choosePromotions, githubReader, readEvidence, rewriteBranch } from './promote.mjs';
import { branchObjects, missingCredentials, R2Error, runUpload } from './r2.mjs';

const REPO_ROOT = fileURLToPath(new URL('../../', import.meta.url));
const DEV_KEY = 'keys/dev/packs.key';
const DEV_CERT = 'keys/dev/packs.cert.json';
const BRANCH_README = `# vendored

Generated by \`.github/workflows/release-packs.yml\` and never edited by hand. Per pack:
\`<id>/<version>/\` is the vendored set unpacked, \`<id>/<version>.tar.gz\` the archive,
\`<id>/index.json\` the pack index and \`<id>/index.sig.json\` its signature. \`docs/release.md\` on
\`main\` describes the format.
`;

const sha256 = (buf) => createHash('sha256').update(buf).digest('hex');

function parseArgs(args, known) {
  const opts = {};
  for (let i = 0; i < args.length; i += 2) {
    const name = args[i]?.replace(/^--/, '');
    if (!args[i]?.startsWith('--') || !known.includes(name)) throw new ReleaseError(`unknown argument ${args[i]}`);
    if (args[i + 1] === undefined) throw new ReleaseError(`${args[i]} needs a value`);
    opts[name] = args[i + 1];
  }
  return opts;
}

// Every pack directory under packsDir with its pack.json fields, validated before anything is built.
function readPacks(packsDir) {
  const ids = readdirSync(packsDir).filter((n) => lstatSync(join(packsDir, n)).isDirectory()).sort();
  const packs = [];
  const errors = [];
  for (const id of ids) {
    try {
      const file = join(packsDir, id, 'pack.json');
      if (!existsSync(file)) throw new ReleaseError(`${id}: no pack.json`);
      let json;
      try { json = JSON.parse(readFileSync(file, 'utf8')); } catch (e) { throw new ReleaseError(`${id}: pack.json does not parse: ${e.message}`); }
      packs.push({ id, ...packFields(id, json) });
    } catch (e) {
      if (!(e instanceof ReleaseError || e instanceof IndexError)) throw e;
      errors.push(e.message);
    }
  }
  if (errors.length) throw new ReleaseError(errors.join('\n'));
  return packs;
}

const onBranch = (repo, commit, path) => commit !== null && (() => {
  try { git(repo, ['cat-file', '-e', `${commit}:${path}`]); return true; } catch { return false; }
})();

// With content, each published pack is vendored afresh and compared with its unpacked set on the
// branch: a change to shipped content under a published version fails, naming the paths.
async function plan(opts, { content = false } = {}) {
  const packsDir = resolve(opts.packs ?? join(REPO_ROOT, 'packs'));
  const packs = readPacks(packsDir);
  const repo = resolve(opts.repo ?? '.');
  const tip = fetchVendored(repo, opts.remote ?? 'origin');
  if (content && tip === null) console.log(`::notice::the remote has no \`${BRANCH}\` branch, so nothing was compared: every pack is to publish`);
  const vendorPack = content ? (await import('../vendor/vendor.mjs')).vendorPack : null;
  const scratch = content ? mkdtempSync(join(tmpdir(), 'release-plan-')) : null;
  let changed = 0;
  try {
    for (const p of packs) {
      if (!onBranch(repo, tip, `${p.id}/${p.version}`)) { console.log(`publish ${p.id} ${p.version}`); continue; }
      if (!content) { console.log(`published ${p.id} ${p.version}`); continue; }
      const work = join(scratch, p.id);
      const candidate = join(work, 'candidate');
      const published = join(work, 'published');
      mkdirSync(candidate, { recursive: true });
      mkdirSync(published);
      vendorPack(join(packsDir, p.id), work);
      execFileSync('tar', ['-xzf', join(work, `${p.id}-${p.version}.tar.gz`), '-C', candidate]);
      git(repo, ['archive', '--format=tar', '-o', join(work, 'published.tar'), `${tip}:${p.id}/${p.version}`]);
      execFileSync('tar', ['-xf', join(work, 'published.tar'), '-C', published]);
      const d = compareTrees(published, candidate);
      if (d) changed++;
      console.log(`published ${p.id} ${p.version} ${d ? `CHANGED: ${d}` : 'unchanged'}`);
    }
  } finally {
    if (scratch) rmSync(scratch, { recursive: true, force: true });
  }
  if (changed) console.log(`::error::${changed} pack(s) changed shipped content under a published version; bump each one's pack.json version`);
  return changed ? 1 : 0;
}

async function build(opts) {
  if (!opts.out) throw new ReleaseError('build needs --out <dir>');
  const packsDir = resolve(opts.packs ?? join(REPO_ROOT, 'packs'));
  const out = resolve(opts.out);
  if (existsSync(out) && readdirSync(out).length) throw new ReleaseError(`${out} is not empty`);
  const packs = readPacks(packsDir);
  const sourceCommit = git(packsDir, ['rev-parse', 'HEAD']).trim();
  const { vendorPack } = await import('../vendor/vendor.mjs');
  const built = [];
  for (const p of packs) {
    const r = vendorPack(join(packsDir, p.id), out);
    const archive = `${p.id}-${p.version}.tar.gz`;
    unlinkSync(join(out, `${p.id}-${p.version}.sha256`));
    built.push({ ...p, archive, sha256: r.sha256, size: r.size });
    console.log(`built ${p.id} ${p.version} ${r.size} ${r.sha256}`);
  }
  writeFileSync(join(out, 'packs.json'), JSON.stringify({ sourceCommit, packs: built }, null, 2) + '\n');
  const sums = [...built.map((b) => `${b.sha256}  ${b.archive}`), `${sha256(readFileSync(join(out, 'packs.json')))}  packs.json`];
  writeFileSync(join(out, 'SHA256SUMS'), sums.join('\n') + '\n');
  console.log(`${built.length} packs built from ${sourceCommit}`);
  return 0;
}

function checkSums(dir) {
  const listed = new Map();
  for (const line of readFileSync(join(dir, 'SHA256SUMS'), 'utf8').split('\n').filter(Boolean)) {
    const m = /^([0-9a-f]{64}) {2}([^/]+)$/.exec(line);
    if (!m) throw new ReleaseError(`SHA256SUMS line is malformed: ${line}`);
    listed.set(m[2], m[1]);
  }
  for (const [file, hex] of listed) {
    if (!existsSync(join(dir, file)) || sha256(readFileSync(join(dir, file))) !== hex) throw new ReleaseError(`${file} does not match SHA256SUMS`);
  }
  if (!listed.has('packs.json')) throw new ReleaseError('SHA256SUMS does not cover packs.json');
  const manifest = JSON.parse(readFileSync(join(dir, 'packs.json'), 'utf8'));
  for (const p of manifest.packs) {
    if (listed.get(p.archive) !== p.sha256) throw new ReleaseError(`${p.archive} is not covered by SHA256SUMS`);
  }
  return manifest;
}

// Every regular file under dir as path -> "sha256 mode", mode reduced to 644 or 755 as the
// vendored set and git both record it.
function treeManifest(dir) {
  const out = new Map();
  const walk = (rel) => {
    for (const name of readdirSync(join(dir, rel)).sort()) {
      const path = rel ? `${rel}/${name}` : name;
      const st = lstatSync(join(dir, path));
      if (st.isDirectory()) walk(path);
      else out.set(path, `${sha256(readFileSync(join(dir, path)))} ${st.mode & 0o111 ? '755' : '644'}`);
    }
  };
  walk('');
  return out;
}

// What differs between the published tree and a candidate one, as "differing: …; missing: …;
// extra: …" with paths in byte order, or null when the two hold the same files.
export function compareTrees(published, candidate) {
  const a = treeManifest(published);
  const b = treeManifest(candidate);
  const byBytes = (x, y) => Buffer.compare(Buffer.from(x), Buffer.from(y));
  const differing = [...a.keys()].filter((k) => b.has(k) && a.get(k) !== b.get(k)).sort(byBytes);
  const missing = [...a.keys()].filter((k) => !b.has(k)).sort(byBytes);
  const extra = [...b.keys()].filter((k) => !a.has(k)).sort(byBytes);
  const parts = [['differing', differing], ['missing', missing], ['extra', extra]].filter(([, l]) => l.length).map(([n, l]) => `${n}: ${l.join(', ')}`);
  return parts.length ? parts.join('; ') : null;
}

// The instant the self-check verifies at: the clock, or --now, which exists for tests that sign
// with a certificate whose window is not today's. publishedAt never reads it.
function selfCheckInstant(now) {
  if (now === undefined) return new Date();
  const t = Date.parse(now);
  if (Number.isNaN(t)) throw new ReleaseError(`--now "${now}" is not a date`);
  return new Date(t);
}

function signingKey(opts) {
  const keyPath = opts.key ?? process.env.CN_PACKS_KEY;
  const certPath = opts.cert ?? process.env.CN_PACKS_CERT;
  if (!keyPath !== !certPath) throw new ReleaseError('CN_PACKS_KEY and CN_PACKS_CERT (or --key and --cert) are set together or not at all');
  const dev = !keyPath;
  if (dev) console.log(`signing with the development key ${DEV_KEY} (trusted by no member)`);
  const key = parsePrivateKey(readFileSync(dev ? join(REPO_ROOT, DEV_KEY) : keyPath, 'utf8'));
  const certificate = JSON.parse(readFileSync(dev ? join(REPO_ROOT, DEV_CERT) : certPath, 'utf8'));
  return { key, certificate, dev };
}

function publish(opts) {
  if (!opts.archives || !opts.roots) throw new ReleaseError('publish needs --archives <dir> and --roots <dir>');
  const archives = resolve(opts.archives);
  const manifest = checkSums(archives);
  const roots = readRoots(resolve(opts.roots));
  const { key, certificate, dev } = signingKey(opts);
  console.log(`signing key id ${keyId(key.publicKey)}`);
  const repo = resolve(opts.repo ?? '.');
  const remote = opts.remote ?? 'origin';
  const branch = openBranch(repo, remote);
  const { tree, scratch } = branch;
  try {

    const pending = [];
    const conflicts = [];
    for (const p of manifest.packs) {
      const indexFile = join(tree, p.id, 'index.json');
      const previous = existsSync(indexFile) ? readIndex(readFileSync(indexFile)) : null;
      const entry = previous?.versions.find((e) => e.version === p.version);
      if (entry || existsSync(join(tree, p.id, p.version))) {
        if (!entry) conflicts.push(`${p.id} ${p.version} is on ${BRANCH} but not in its index`);
        else if (!existsSync(join(tree, p.id, p.version))) conflicts.push(`${p.id} ${p.version} is in its index but its unpacked set is not on ${BRANCH}`);
        else if (entry.sha256 !== p.sha256) {
          const unpacked = join(scratch, 'compare', p.id);
          mkdirSync(unpacked, { recursive: true });
          execFileSync('tar', ['-xzf', join(archives, p.archive), '-C', unpacked]);
          const d = compareTrees(join(tree, p.id, p.version), unpacked);
          if (d) conflicts.push(`${p.id} ${p.version} is already published with different content (${d}). Bump the version.`);
        }
        continue;
      }
      pending.push({ ...p, previous });
    }
    if (conflicts.length) throw new ReleaseError(`refusing to overwrite a published version:\n${conflicts.join('\n')}`);
    if (!pending.length) {
      console.log('nothing to publish');
      writeSummary(opts.summary, [], key, dev);
      return 0;
    }

    const publishedAt = new Date().toISOString().replace(/\.\d{3}Z$/, 'Z');
    const written = [];
    for (const p of pending) {
      const dir = join(tree, p.id, p.version);
      mkdirSync(dir, { recursive: true });
      execFileSync('tar', ['-xzf', join(archives, p.archive), '-C', dir]);
      copyFileSync(join(archives, p.archive), join(tree, p.id, `${p.version}.tar.gz`));
      const next = addVersion(p.previous ?? newIndex(p.id), {
        packJson: { version: p.version, minEngineVersion: p.minEngineVersion, requires: p.requires },
        sha256: p.sha256, size: p.size, publishedAt, sourceCommit: manifest.sourceCommit,
      });
      assertSerialAdvances(p.previous, next);
      const bytes = serialize(next);
      writeFileSync(join(tree, p.id, 'index.json'), bytes);
      writeFileSync(join(tree, p.id, 'index.sig.json'), JSON.stringify(signIndex(bytes, key, certificate), null, 2) + '\n');
      if (!existsSync(join(tree, 'README.md'))) writeFileSync(join(tree, 'README.md'), BRANCH_README);
      branch.writeBranchCommit([p.id, 'README.md'], `Release ${p.id} ${p.version}`);
      written.push({ ...p, serial: next.serial });
      console.log(`Release ${p.id} ${p.version}`);
    }

    branch.selfCheck(written, roots, selfCheckInstant(opts.now));
    branch.push();
    console.log(`pushed ${written.length} release commit(s) to ${BRANCH}`);

    writeSummary(opts.summary, written, key, dev);
    return 0;
  } finally {
    branch.close();
  }
}

// Makes R2 hold what the branch holds: every version's archive and each pack's index pair, then
// reads them back through the CDN. The scope is the branch, so a run that died after a publish
// pushed is healed by the next.
async function upload(opts) {
  if (!opts.r2 || !opts.roots) throw new ReleaseError('upload needs --r2 <bucket|dry-run> and --roots <dir>');
  if (opts.r2 !== 'dry-run') {
    const missing = missingCredentials(process.env);
    if (missing) {
      console.log(`::error::${missing}`);
      return 1;
    }
  }
  const roots = readRoots(resolve(opts.roots));
  const repo = resolve(opts.repo ?? '.');
  const tip = fetchVendored(repo, opts.remote ?? 'origin');
  if (!tip) {
    console.log(`nothing on ${BRANCH} to upload`);
    return 0;
  }
  const objects = branchObjects((path) => showFile(repo, tip, path), packIds(repo, tip));
  const report = await runUpload({ objects, target: opts.r2, env: process.env, roots, now: new Date(), log: (l) => console.log(l) });
  if (opts.summary) {
    const lines = ['## R2 upload', ''];
    if (opts.r2 === 'dry-run') lines.push(`Dry run: ${objects.length} object(s) would be PUT.`);
    else {
      const puts = report.reduce((n, r) => n + r.put.length, 0);
      const byEtag = report.reduce((n, r) => n + r.byEtag, 0);
      lines.push(`Bucket \`${opts.r2}\` at ${tip.slice(0, 12)} of ${BRANCH}: ${puts} object(s) PUT, ${byEtag} found equal by ETag alone, every object read back through the CDN.`, '');
      for (const r of report) lines.push(`- ${r.id}: ${r.put.length ? `PUT ${r.put.map((k) => `\`${k}\``).join(', ')}` : 'nothing PUT'}; ${r.skipped.length} skipped (${r.byEtag} by ETag)`);
    }
    appendFileSync(opts.summary, lines.join('\n') + '\n\n');
  }
  return 0;
}

const CANARIES = join(REPO_ROOT, 'tools/release/canaries.json');
const readJsonFile = (path) => JSON.parse(readFileSync(path, 'utf8'));
const appendSummary = (file, lines) => { if (file) appendFileSync(file, lines.join('\n') + '\n\n'); };

function branchIndexes(repo, remote) {
  const tip = fetchVendored(repo, remote);
  return packIds(repo, tip).map((pack) => ({ pack, index: readIndex(showFile(repo, tip, `${pack}/index.json`)) }));
}

async function evidence(opts) {
  if (!opts.out) throw new ReleaseError('evidence needs --out <file>');
  const config = readJsonFile(opts.canaries ?? CANARIES);
  const indexes = branchIndexes(resolve(opts.repo ?? '.'), opts.remote ?? 'origin');
  const ev = await readEvidence({ indexes, config, reader: githubReader({ token: process.env.GITHUB_TOKEN }) });
  writeFileSync(opts.out, JSON.stringify(ev, null, 2) + '\n');
  console.log(`${ev.candidates.length} candidate(s) read from ${config.canaries.length} canary repo(s) and ${config.blockers.repo}`);
  appendSummary(opts.summary, ['## Canary evidence', '', `Read at ${ev.readAt}: ${ev.candidates.length} candidate(s).`, '',
    ...ev.candidates.map((c) => `- ${c.pack} ${c.version}: ${c.canaries.flatMap((k) => k.workflows.map((w) => `${k.repo} ${w.file} ${w.run ? w.run.conclusion : 'no run'}`)).join(', ') || 'no workflow listed'}${c.blockers.length ? `; blockers ${c.blockers.map((b) => `#${b.number}`).join(', ')}` : ''}`)]);
  return 0;
}

// promote --evidence <file>, or a dispatch: promote|revoke --pack --version --by.
function rewrite(action, opts) {
  if (!opts.roots) throw new ReleaseError(`${action} needs --roots <dir>`);
  const repo = resolve(opts.repo ?? '.');
  const remote = opts.remote ?? 'origin';
  let changes;
  let declined = [];
  if (action === 'promote' && opts.evidence) {
    const config = readJsonFile(opts.canaries ?? CANARIES);
    const decision = choosePromotions(readJsonFile(opts.evidence), config);
    if (decision.verdict) {
      console.log(decision.verdict);
      appendSummary(opts.summary, ['## Promotion', '', decision.verdict]);
      return 0;
    }
    declined = decision.declined;
    for (const d of declined) console.log(`not promoted: ${d.pack} ${d.version}: ${d.reason}`);
    changes = decision.promote.map((p) => ({ ...p, action }));
  } else {
    if (!opts.pack || !opts.version || !opts.by) throw new ReleaseError(`${action} needs --pack, --version and --by together${action === 'promote' ? ', or --evidence <file>' : ''}`);
    changes = [{ pack: opts.pack, version: opts.version, action, by: opts.by }];
  }
  const { key, certificate } = signingKey(opts);
  const written = changes.length ? rewriteBranch({
    repo, remote, roots: readRoots(resolve(opts.roots)), key, certificate, changes, now: new Date(), skipStale: Boolean(opts.evidence), log: (l) => console.log(l),
  }) : [];
  if (!written.length) console.log(`nothing to ${action}`);
  appendSummary(opts.summary, [action === 'promote' ? '## Promotion' : '## Revocation', '', `Signing key id \`${keyId(key.publicKey)}\`.`, '',
    ...(written.length ? written.map((w) => `- ${w.message} (index serial ${w.serial})`) : [`Nothing to ${action}.`]),
    ...declined.map((d) => `- not promoted: ${d.pack} ${d.version}: ${d.reason}`)]);
  return 0;
}

function writeSummary(file, written, key, dev) {
  if (!file) return;
  const lines = [
    '## Pack release',
    '',
    `Signing key id \`${keyId(key.publicKey)}\`${dev ? ' (the development key, trusted by no member)' : ''}.`,
    '',
    written.length ? `${written.length} pack version(s) published:` : 'Nothing to publish.',
    ...written.map((p) => `- ${p.id} ${p.version} (index serial ${p.serial})`),
    '',
  ];
  appendFileSync(file, lines.join('\n'));
}

async function main([cmd, ...args]) {
  if (cmd === 'plan') return plan(parseArgs(args.filter((a) => a !== '--content'), ['packs', 'repo', 'remote']), { content: args.includes('--content') });
  if (cmd === 'build') return build(parseArgs(args, ['packs', 'out']));
  if (cmd === 'evidence') return evidence(parseArgs(args, ['out', 'canaries', 'repo', 'remote', 'summary']));
  if (cmd === 'promote') return rewrite('promote', parseArgs(args, ['evidence', 'canaries', 'pack', 'version', 'by', 'roots', 'key', 'cert', 'repo', 'remote', 'summary']));
  if (cmd === 'revoke') return rewrite('revoke', parseArgs(args, ['pack', 'version', 'by', 'roots', 'key', 'cert', 'repo', 'remote', 'summary']));
  if (cmd === 'upload') return upload(parseArgs(args, ['r2', 'roots', 'repo', 'remote', 'summary']));
  if (cmd === 'publish') return publish(parseArgs(args, ['archives', 'roots', 'key', 'cert', 'repo', 'remote', 'summary', 'now']));
  console.error('usage: release.mjs plan | build --out <dir> | publish --archives <dir> --roots <dir> | upload --r2 <bucket|dry-run> --roots <dir> | evidence --out <file> | promote | revoke (see the header)');
  return 2;
}

if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
  main(process.argv.slice(2)).then((code) => { process.exitCode = code; }).catch((e) => {
    if (!(e instanceof ReleaseError || e instanceof IndexError || e instanceof SignError || e instanceof R2Error || e.code === 'ENOENT')) throw e;
    console.error(`release.mjs: ${e.message}`);
    process.exitCode = 1;
  });
}
